### ISSUE TITLE
Use of shellcheck action to check linked files

### ISSUE THREAD

**Issue by bretton** [depenguin-me/depenguin-builder#5]
We are using this [shellcheck action](https://github.com/marketplace/actions/shellcheck) with 196 stars as follows
```
name: Shellcheck

on: [ pull_request ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC1091 -e SC2034 -e SC2154 -e SC3040 -e SC2148
      with:
        scandir: '.'
        additional_files: 'customfiles/sample.depenguin_settings.sh'
        check_together: 'yes'
```

We are excluding problematic tests, which has criticism.

There is also [this other shellcheck action](https://github.com/marketplace/actions/action-shellcheck) with 1 star, which is used as follows, and may allow passing in the "-x" parameter
```
name: Shellcheck-other

on: [ pull_request ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: sudo-bot/action-shellcheck@latest
      with:
        # https://github.com/koalaman/shellcheck#how-to-use
        cli-args: "--format=checkstyle --severity=info script.sh"
```

*edit: fixed for correct link to original shellcheck in use
